from centos:latest

ADD configuration-file/config.sh /bin
ADD output-file/output.sh /bin
ADD example1/exampleTool1 /bin
ADD example1/exampleTool2 /bin
ADD list/list.sh /bin
ADD output-flag-separator/output-flag.sh /bin
